_format_version: "2.1"
_transform: true

services:
- name: api
  url: http://api:3000
  routes:
  - name: my-route
    paths:
    - /api

# consumers:
# - username: api
#   keyauth_credentials:
#   - key: my-key

# https://docs.konghq.com/hub/kong-inc/zipkin/
plugins:
- name: zipkin
  config: 
    http_endpoint: http://otel-agent:9411/api/v2/spans
    sample_ratio: 1
    include_credential: true
    traceid_byte_count: 16
    header_type: w3c

- name: prometheus

  # https://www.nginx.com/blog/opentracing-nginx-plus/

  # https://docs.nginx.com/nginx/admin-guide/dynamic-modules/opentracing/

  # https://docs.konghq.com/hub/kong-inc/prometheus/