[sources.in]
  type = "docker" # required
  include_containers = ["api", "gateway", "kibana", "db"]

[sinks.out]
  inputs = ["in"]
  type = "elasticsearch"
  host = "http://elasticsearch:9200"
  index = "vector-%Y-%m-%d"