scrape_configs:
  - job_name: Container Metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
  - job_name: "dns"
    scrape_interval: 10s
    static_configs:
      - targets: ["dns:9153"]
  - job_name: Kong Gateway
    scrape_interval: 5s
    static_configs:
      - targets: ["gateway:8001"]
